# Generated by Django 4.0.3 on 2022-04-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profession_user_prfssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.contact'),
        ),
    ]
