# Generated by Django 4.0.3 on 2022-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='No image', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
