# Generated by Django 4.0.3 on 2022-04-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_user_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usr',
        ),
    ]
