# Generated by Django 4.0.3 on 2022-04-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_user_gend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gend',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='registration.gender'),
        ),
    ]
