# Generated by Django 4.0.3 on 2022-04-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_user_gend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addres',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prfssn',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.profession'),
        ),
    ]
