# Generated by Django 4.0.3 on 2022-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_user_addres_alter_user_prfssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
