# Generated by Django 4.0.3 on 2022-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
