# Generated by Django 3.2.12 on 2022-11-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='service',
        ),
    ]
