# Generated by Django 3.2.12 on 2022-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_rename_user_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='rqstd_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
