# Generated by Django 3.2.12 on 2022-11-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_rename_rqstd_service_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
            ],
        ),
    ]
