# Generated by Django 3.2.12 on 2022-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
