# Generated by Django 3.2.12 on 2022-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20221106_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='uploaded_on',
            field=models.DateField(auto_now=True),
        ),
    ]
