# Generated by Django 3.2.12 on 2022-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_alter_staff_uploaded_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
