# Generated by Django 3.2.12 on 2022-11-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_faqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faqs',
            new_name='faq',
        ),
    ]
