# Generated by Django 3.2.12 on 2022-11-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_rename_faqs_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
    ]
