# Generated by Django 3.2.12 on 2022-11-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=5000)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
