# Generated by Django 3.2.12 on 2022-11-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='answer',
            new_name='desc',
        ),
    ]
