# Generated by Django 3.2.12 on 2022-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='uploads/default-image.webp', upload_to='uploads/%Y/%m/%d/')),
                ('desc', models.CharField(max_length=280, null=True)),
            ],
        ),
    ]
