# Generated by Django 3.2.12 on 2022-11-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_auto_20221118_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='usernames',
            field=models.CharField(default='hajaweka majina', max_length=50),
            preserve_default=False,
        ),
    ]
