# Generated by Django 3.2.12 on 2022-11-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_auto_20221121_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='usr',
            field=models.ManyToManyField(blank=True, null=True, to='registration.user'),
        ),
    ]
