# Generated by Django 3.2.12 on 2022-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_auto_20221122_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
    ]
