# Generated by Django 3.2.12 on 2022-11-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='button',
        ),
    ]
