# Generated by Django 3.2.12 on 2022-11-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_remove_service_button'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='product',
        ),
    ]
