# Generated by Django 3.2.12 on 2022-11-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_rename_service_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comparable_price',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
