# Generated by Django 3.2.12 on 2022-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_auto_20221124_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comparable_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
