# Generated by Django 3.2.12 on 2022-11-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_alter_product_comparable_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='usr',
        ),
        migrations.AddField(
            model_name='user',
            name='usr_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.product'),
        ),
    ]
