# Generated by Django 3.2.12 on 2022-11-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_auto_20221125_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usr_car',
            new_name='usr_cart',
        ),
    ]
